### ISSUE TITLE
Error filtering the status in getOrderHistory

### ISSUE THREAD

**Issue by nitzantomer** [kinecosystem/kin-devplatform-marketplace-server#10]
The issue was described in the https://github.com/kinecosystem/marketplace-server repo, but we were unable to reproduce it there.  
Issue details: https://github.com/kinecosystem/marketplace-server/issues/170

**Comment by yosriz** [comment]
fixed at https://github.com/kinecosystem/kin-devplatform-marketplace-server/pull/11

**Comment by chancity** [comment]
Awesome, thanks
